name: dev

on:
  push:
    branches:
      - main
    paths: ["src/**", "docker/**", "terraform/**"]

  workflow_dispatch:

jobs:
  build:
    name: Run tests and build application
    runs-on: ubuntu-latest
    steps:
      - name: Clone code from GitHub repository inside GitHub actions runner
        uses: actions/checkout@v3

      - name: Set up jdk 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Authenticate to AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Run tests and build jar file
        run: mvn clean install

      - name: Push image to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ vars.DOCKER_USERNAME }} --password-stdin
          docker build --platform linux/arm64 -t ${{ vars.DOCKER_USERNAME }}/${{ vars.DOCKER_IMAGE_NAME }}:latest .
          docker push ${{ vars.DOCKER_USERNAME }}/${{ vars.DOCKER_IMAGE_NAME }}:latest